Hometask-1
romagusev11/smart-home-2021 pull request #1
Opened 2021-03-10 19:31 UTC by romagusev11

2021-03-10 19:37 UTC, romagusev11 commented
Во время выполнения задания у меня возник вопрос:
Сперва происходит конфигурация - на этом этапе навешиваются обработчики событий, то есть они не знают об объекте умного дома, так как его создание происходит уже на этапе чтения. Такой подход мне кажется неправильным, так как бессмысленно каждый раз указывать обработчику какой именно умный дом он обрабатывает. Стоит ли поэтому разделить объявление умного дома (на этапе конфигурации) и его инициализацию на этапе чтения?

2021-03-10 19:43 UTC, romagusev11 commented
Обработчики событий выполняют любые команды над умным домом, то есть обработка датчика лампочки потенциально может потенциально взорвать дом. Стоит вынести все разрешенные команды в отдельный список, но мне пока непонятно как правильно это сделать.

2021-03-10 19:44 UTC, romagusev11 commented
И вообще нужно ли это?

2021-03-14 18:58 UTC, a-ivanov requested changes

2021-03-14 18:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
SRP: цикл обработки - отдельная отвественность.

2021-03-14 18:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/DoorEventHandler.java
> +                            if (room.getName().equals("hall")) {
SRP: отдельная ответственность

2021-03-14 18:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private final Map<SensorEventType, List<EventHandler>> subscribers;
Сложно для такой задачи. Плюс усложнение с точки зрения добавления новых обработчиков. Лучше переделайте в список.

2021-03-14 18:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/io/FileSmartHomeReader.java
> +    public SmartHome getSmartHome() {
`@Override`

2021-03-14 18:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/io/FileSmartHomeReader.java
> +    public SmartHome getSmartHome() {
Лучше назвать read/load, get - это когда возвращают ссылку на уже существующий объект.

2021-03-14 18:59 UTC, a-ivanov commented
> Во время выполнения задания у меня возник вопрос:
> Сперва происходит конфигурация - на этом этапе навешиваются обработчики событий, то есть они не знают об объекте умного дома, так как его создание происходит уже на этапе чтения. Такой подход мне кажется неправильным, так как бессмысленно каждый раз указывать обработчику какой именно умный дом он обрабатывает. Стоит ли поэтому разделить объявление умного дома (на этапе конфигурации) и его инициализацию на этапе чтения?

Мне кажется, что это абсолютно ок сначала читать состояние дома, а потом привязывать к нему обработчики. У нас нет задачи работать с разными домами.

2021-03-18 05:23 UTC, a-ivanov approved these changes

2021-03-18 05:23 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/HandlerCollectionImpl.java
> +public class HandlerCollectionImpl implements HandlerCollection{
Имплементация дублирует функциональность стандартной коллекции, можно обойтись `List`.

2021-03-22 10:36 UTC, merged