Hometask-3
romagusev11/smart-home-2021 pull request #4
Opened 2021-03-24 23:19 UTC by romagusev11

2021-03-31 05:42 UTC, a-ivanov requested changes
Не вижу декоратор сигнализации.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +public class Alarm implements AlarmState {
Разве сигнализация является своим состоянием? Состояние - это деталь реализации сигнализации, не имплементируйте этот интерфейс. API сигнализации может отличаться от API состояния.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +    public AlarmState getState() {
Сделайте методы для работы с сигнализацией вместо этого как обсуждали в группе.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +    public void changeState(AlarmState state) {
Package private.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +    public void setCode(String code) {
Package private, инкапсуляция.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/sensors/AlarmConnectedSensorHandler.java
> +        logger.log("Sending sms... Alarm: " + event.toString());
В отдельный класс, SRP.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EventLoopImpl.java
> +        this.alarmHandler = alarmHandler;
Нарушение OCP, сделайте так, чтобы цикл работал только со списком обработчиков.

2021-03-31 05:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmReactor.java
> +public interface AlarmReactor {
Такого не было в задании. Напишите декоратор.

2021-03-31 19:59 UTC, romagusev11 commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmReactor.java
> +public interface AlarmReactor {
Это было на лекции - нам рассказали про паттерн(забыл название), чтобы избавится от зависимости между декоратором и состояниями сигнализации.

2021-03-31 20:01 UTC, romagusev11 commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmReactor.java
> +public interface AlarmReactor {
public class AlarmConnectedHandler implements EventHandler - вроде декоратор?

2021-04-01 06:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmReactor.java
> +public interface AlarmReactor {
> Это было на лекции - нам рассказали про паттерн(забыл название), чтобы избавится от зависимости между декоратором и состояниями сигнализации.

Хм, тогда лучше ещё раз обсудим в группе, чтобы было понимание. Просто, на мой взгляд, такой зависимости не будет, если декоратор работает с публичным API сигнализации, которая внутри делегирует / проверяет состояния. Тогда классы состояний вообще package private могут быть.

2021-04-02 04:54 UTC, a-ivanov requested changes

2021-04-02 04:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +    public boolean isCorrectCode(String code) {
Package private, клиент не должен иметь возможности проверить код.

2021-04-02 04:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +    public void sendMessage(String message) {
Если сигнализация не использует Sender, тогда это SRP. Передайте его полем туда, где он используется.

2021-04-09 16:13 UTC, a-ivanov approved these changes

2021-04-15 07:12 UTC, merged