Hometask-5
romagusev11/smart-home-2021 pull request #6
Opened 2021-04-07 21:16 UTC by romagusev11

Я решил использовать уже использующийся интерфейс CommandSender и прямой доступ у сигнализации при работе с пультом, так как я считаю между пультом (отправка событий во внешний мир) и eventLoop-ом (обработка событий из внешнего мира) не должно быть никакой связи.
Но теперь при закрытии входной двери при помощи пульта в доме не выключается свет. Я считаю это правильным поведением так как на самом деле при закрытии двери сенсор должен (но не в текущей реализации) отправить обратно событие типа дверь закрыта и соответсвенно тогда его обработает eventLoop и уже выключит свет.

2021-04-16 06:54 UTC, a-ivanov requested changes
См. обсуждение в группе, создайте необходимые бины.

2021-04-16 06:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/remotecontrol/RemoteControlImpl.java
> +    public RemoteControlImpl addCommand(String buttonCode, RemoteControlCommand command) {
Возвращайте тип интерфейса, не имплементации.

2021-04-16 17:06 UTC, romagusev11 commented on src/main/java/ru/sbt/mipt/oop/remotecontrol/RemoteControlImpl.java
> +    public RemoteControlImpl addCommand(String buttonCode, RemoteControlCommand command) {
Но у интерфейса нет метода addComand, а мне хотелось сделать такую цепочку:
        remoteControl = new RemoteControlImpl()
                .addCommand("A", new ActivateAlarmCommand(alarm, code))
                .addCommand("B", new SetAlarmOnAlertCommand(alarm))
                .addCommand("C", new CloseFrontDoorCommand(smartHome, sender))
                .addCommand("D", new CloseFrontDoorCommand(smartHome, sender))
                .addCommand("1", new TurnLightInRoomOnCommand(smartHome, sender, "hall"))
                .addCommand("2", new TurnLightOffCommand(smartHome, sender))
                .addCommand("3", new TurnLightOnCommand(smartHome, sender));

2021-04-20 13:28 UTC, a-ivanov requested changes
Создайте бины для RemoteControl, см. гайд.

2021-04-20 13:28 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/remotecontrol/RemoteControlImpl.java
> +    public RemoteControlImpl addCommand(String buttonCode, RemoteControlCommand command) {
Для этого обычно делают отдельный класс - Builder (https://refactoring.guru/design-patterns/builder). addCommand - это не бизнес-логика реализации RemoteControl, это утилита, поэтому она не должна быть в публичном API.

2021-04-28 21:26 UTC, romagusev11 commented on src/main/java/ru/sbt/mipt/oop/remotecontrol/RemoteControlImpl.java
> +    public RemoteControlImpl addCommand(String buttonCode, RemoteControlCommand command) {
Теперь понял

2021-04-28 21:54 UTC, romagusev11 commented on src/main/java/ru/sbt/mipt/oop/AppConfiguration.java
>  }
По-моему это самый простой способ связать кнопки с командами (не получилось нормально раскидать их всех на свои бины)

2021-04-30 06:45 UTC, a-ivanov requested changes
Ок, ещё нужен бин регистра, в котором будет зарегистрирован RemoteControl.

2021-05-10 18:18 UTC, romagusev11 commented
Что-то я совсем забыл про это :-)

2021-05-11 16:26 UTC, a-ivanov approved these changes

2021-05-11 16:38 UTC, merged